package com.activitymonitor;



import android.content.Context;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.util.Log;

public class AccelerometerReceiver implements SensorEventListener {
	/**
	 * Tag for use in logging and debugging the output generated by this class.
	 */
	public static final String TAG = "AccelerometerReceiver";
	private Context mContext;
	private String labelName;



	/**
	 * Constructs an object of type {@code AccelerometerReceiver}.
	 * @param context {@code Context}
	 */
	public AccelerometerReceiver(Context context, String labelName) {
		mContext = context;
		this.labelName = labelName;
		Log.i(TAG,"LabelName = " + labelName);

	}

	@Override
	public void onAccuracyChanged(Sensor arg0, int arg1) {
		// TODO Auto-generated method stub

	}

	@Override
	public void onSensorChanged(SensorEvent event) {
		// TODO Auto-generated method stub
		// InteractionsDB db = new InteractionsDB(mContext);
		// db.addInteraction(new LocationInteraction(timestamp, provider, location.getLatitude(),
		// location.getLongitude(), location.getAccuracy()));
		// How to add to the database!!!!
		// Log.i(TAG,"x , y and z");
	}

}
