package com.activitymonitor;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ComponentName;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.IntentFilter;
import android.media.AudioManager;
import android.media.Ringtone;
import android.media.RingtoneManager;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.util.Log;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

public class ActivityGatherer extends Activity {
	/**
	 * Tag for use in logging and debugging the output generated by this class.
	 */
	public final static String TAG = "ActivityGatherer";
	private boolean mIsRecording = false;
	private String labelName;
	HeadSetReceiver mMediaButtonReceiver = new HeadSetReceiver();


	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_activity_gatherer);
	    ((AudioManager)getSystemService(AUDIO_SERVICE)).registerMediaButtonEventReceiver(new ComponentName(
                this,
                HeadSetReceiver.class));
	    IntentFilter filter = new IntentFilter(Intent.ACTION_MEDIA_BUTTON);
	    HeadSetReceiver r = new HeadSetReceiver();
	    filter.setPriority(1000);
	    registerReceiver(r, filter);
	}


	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.activity_gatherer, menu);
		return true;
	}
	/**
	 * 
	 * @param view
	 */
	public void setService(View view){
		// Cast View v to Button
		Button thisButton = (Button) view;
		Button labelButton = (Button) ActivityGatherer.this.findViewById(R.id.latestbutton);
		EditText edtLabelName = (EditText) ActivityGatherer.this.findViewById(R.id.edtLabelName);
		//Set the label name for the next session of recording data
		labelName = edtLabelName.getText().toString();
		
		//Still need to improve this if statement but it will do for now!
		if(labelName.equals("")|| labelName.contains(" ")){
			//Inform the user to input a label name
			createLabelNameDialog();
		}
		else{

			//Stop service gathering accelerometer data
			if(mIsRecording){
				mIsRecording = false;
				thisButton.setText(R.string.record);
				//Need to Stop the service
				stopMainService();
				labelButton.setEnabled(true);
			}
			else{
				mIsRecording = true;
				thisButton.setText(R.string.stop);
				labelButton.setEnabled(false);
				//Inform the user the service has begun to record data with a notification
				try {
					Uri notification = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
					Ringtone r = RingtoneManager.getRingtone(getApplicationContext(), notification);
					r.play();
				} catch (Exception e) {}
				startMainService();

			}
		}

	}
	
	/**
	 * Creates a dialog telling the user that the airplane is turned on.
	 */
	private void createLabelNameDialog() {

		String msg = "You need to input a label name.";
		AlertDialog.Builder builder = new AlertDialog.Builder(ActivityGatherer.this);
		builder.setMessage(msg)
		.setCancelable(false)
		.setPositiveButton("OK", new DialogInterface.OnClickListener() {
			public void onClick(DialogInterface dialog, int id) {
				dialog.cancel();
			}
		});
		AlertDialog alert = builder.create();
		alert.show();


	}


	/**
	 * Starts the gathering service.
	 */
	public void startMainService(){
		Log.d(TAG,"Trying to start the main service");
		Intent intent = new Intent(getApplicationContext(), ActivityGathererService.class);
		intent.putExtra("labelName", labelName);
		startService(intent);
	}

	/**
	 * Stops the gathering service
	 */
	public void stopMainService(){
		Intent intent = new Intent(getApplicationContext(), ActivityGathererService.class);
		stopService(intent);
	}
	/**
	 * Sets the view to display the id of the last record added
	 * to a database
	 * @param v
	 */
	public void latestButtonClick(View v){
		TextView edtLabelName = (TextView) ActivityGatherer.this.findViewById(R.id.txtLatestID);
		SampleDB db = new SampleDB(getApplicationContext());
		String id = db.getLatestID();
		edtLabelName.setText("id = " + id);
	}
	
//	@Override
//	public boolean onKeyDown(int keyCode, KeyEvent event){
//		//Log.i(TAG, "key code =" + keyCode);
//		if (keyCode == KeyEvent.KEYCODE_HEADSETHOOK) {
//			Log.i(TAG, "The media button has been pressed");
//			Button record = (Button) ActivityGatherer.this.findViewById(R.id.recordbutton);
//			setService(record);
//			return true;
//		}
//		
//		 
//		return false;
//	}
}
