package com.activitymonitor;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.KeyEvent;

public class HeadSetReceiver extends BroadcastReceiver {
	/**
	 * Tag for use in logging and debugging the output generated by this class.
	 */
	public static final String TAG = "AccelerometerReceiver";
	
	public HeadSetReceiver(){
		super();
	}

	@Override
	public void onReceive(Context arg0, Intent intent) {
	    String intentAction = intent.getAction();
	    if (!Intent.ACTION_MEDIA_BUTTON.equals(intentAction)) {
	    	Log.i(TAG, "CASE 1: THIS IS NOT AN ACTION MEDIA EVENT");
	        return;
	    }
	    KeyEvent event = (KeyEvent)intent.getParcelableExtra(Intent.EXTRA_KEY_EVENT);
	    if (event == null) {
	    	Log.i(TAG, "CASE 2: THE EVENT WAS NULL");
	        return;
	    }
	    int action = event.getAction();
	    int keyCode = event.getKeyCode() ;

	    if (action == KeyEvent.ACTION_DOWN && keyCode == KeyEvent.KEYCODE_HEADSETHOOK) {
	    // do something
	    	Log.i(TAG, "CASE 3: THIS WORKS!!");
	    }
	    abortBroadcast();
		
	}

}
