package com.activitymonitor;

//
//InteractionsDBHelper.java
//SocialGatherer
//
//Created by Adeeb Umar on 13/03/2013
//Copyright (c) 2012 University of Strathclyde. All rights reserved.
//


import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

/**
 * This class is a helper class for opening/creating/upgrading the sample db.
 * It should be used in conjunction with {@link SampleDB} helper class.
 * @author Adeeb Umar
 * @version 1.0
 * @see SampleDB
 */
public class SampleDBHelper extends SQLiteOpenHelper {
	// All Static variables
	// Database Version
	private static final int DATABASE_VERSION = 5;
	/**
	 * Tag for use in logging and debugging the output generated by this class.
	 */
	public final static String TAG = "SampleDBHelper";
	/**
	 * Name of table in the flat sample db for storing all samples.
	 */
	public final static String TABLE = "sample";
	/**
	 * Id column name.
	 */
	public final static String ID = "_id";
	/**
	 * X column name.
	 */
	public final static String X = "x";
	/**
	 * Y column name.
	 */
	public final static String Y = "y";
	/**
	 * Z column name.
	 */
	public final static String Z = "z";
	/**
	 * Timestamp column name.
	 */
	public final static String TIMESTAMP = "timestamp";
	/**
	 * LabelName column name.
	 */
	public final static String LABELNAME = "labelName";


	/**
	 * Constructs an object of type {@code SampleDBHelper}.
	 * @param context The {@code Context} in which the {@code SampleDBHelper}
	 * object was created.
	 * @param path The absolute path to the sample db.
	 */
	public SampleDBHelper(Context context, String path) {
		super(context, path, null, DATABASE_VERSION);
	}

	/**
	 * Creates new sample table inside the sample db if it doesn't exist
	 * already. Id column is an integer primary key autoincrement column, X is an
	 * REAL column, Y is REAL column, Z is a REAL column, Timestamp is a long column
	 * @param db {@link android.database.sqlite.SQLiteDatabase} object.
	 */
	@Override
	public void onCreate(SQLiteDatabase db) {
		// SQL syntax for creating sample table
		String interSQL = "create table " + TABLE + " (" +
				ID + " integer primary key autoincrement, " +
				X + " real, " +
				Y + " real, " +
				Z + " real, " +
				TIMESTAMP + " integer, " +
				LABELNAME + " text);";
		db.execSQL(interSQL);
	}

	/**
	 * Upgrades the structure of the database. CURRENTLY UNIMPLEMENTED.
	 * @param db {@link android.database.sqlite.SQLiteDatabase} object.
	 * @param oldVersion Id/number of the old version of the db.
	 * @param newVersion Id/number of the new version of the db.
	 */
	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
		Log.w(TAG,
				"Upgrading database from version " + oldVersion + " to "
						+ newVersion + ", which will destroy all old data");
		// Drop older table if existed
		db.execSQL("DROP TABLE IF EXISTS " + TABLE);

		// Create tables again
		onCreate(db);
	}
}