package com.activitymonitor.database;

//
//Sample.java
//ActivityMonitor
//
//Created by Adeeb Umar on 13/03/2013
//Copyright (c) 2012 University of Strathclyde. All rights reserved.
//


import java.lang.StringBuilder;
import java.lang.System;

/**
 * This class represents a sample acquired by the accelerometer.
 * @author Adeeb Umar
 * @version 1.0
 */
public class Sample {
	/**
	 * Tag for use in logging and debugging the output generated by this class.
	 */
	public final static String TAG = "Sample";

	private float x;
	private float y;
	private float z;
	private String timestamp;
	private String activity_type;
	private int activity_id;
	/**
	 * Constructs an object of type {@code Sample}.
	 * @param timestamp the time the sample was recorded
	 * @param x the value of the X axis of the accelerometer
	 * @param y the value of the Y axis of the accelerometer
	 * @param z the value of the Z axis of the accelerometer

	 */
	public Sample(float x, float y, float z,String timestamp, String activity_type, int activity_id ) {
		this.x = x;
		this.y = y;
		this.z = z;
		this.timestamp = timestamp;
		this.activity_type = activity_type;
		this.activity_id = activity_id;
	}

	/**
	 * @return The timestamp of the sample.
	 */
	public String getTimestamp() {
		return timestamp;
	}

	/**
	 * @return The value of the accelerometer along the X
	 * axis
	 */
	public float getX() {
		return x;
	}

	/**
	 * @return The value of the accelerometer along the Y
	 * axis
	 */
	public float getY() {
		return y;
	}

	/**
	 * @return The value of the accelerometer along the Z
	 * axis
	 */
	public float getZ() {
		return z;
	}

	/**
	 *@return The activity_type given to the sample
	 */
	public String getActivityType(){
		return activity_type;
	}
	
	/**
	 *@return The activity_id given to the sample
	 */
	public int getActivityID(){
		return activity_id;
	}

	/**
	 * @return The {@code String} representation of the {@code Sample} object.
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		String NEW_LINE = System.getProperty("line.separator");
		result.append(this.getClass().getName() + " Object {" + NEW_LINE);
		result.append(" x: " + x + NEW_LINE);
		result.append(" y: " + y + NEW_LINE);
		result.append(" z: " + z + NEW_LINE);
		result.append(" timestamp: " + timestamp + NEW_LINE);
		result.append(" activity_type: " + activity_type + NEW_LINE);
		result.append(" activity_id: " + activity_id + NEW_LINE);
		result.append("}");
		return result.toString();
	}

}
