package com.activitymonitor.listeners;



import java.util.Date;

import com.activitymonitor.database.Sample;
import com.activitymonitor.database.SampleDB;
import com.activitymonitor.preferences.Preferences;

import android.content.Context;
import android.content.SharedPreferences;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.util.Log;

public class AccelerometerListener implements SensorEventListener {
	/**
	 * Tag for use in logging and debugging the output generated by this class.
	 */
	public static final String TAG = "AccelerometerReceiver";
	private Context mContext;
	private String activity_type;
	private int activity_id;
	private SampleDB db;



	/**
	 * Constructs an object of type {@code AccelerometerReceiver}.
	 * @param context {@code Context}
	 */
	public AccelerometerListener(Context context) {
		Date date = new Date();
		mContext = context;
		SharedPreferences settings = mContext.getSharedPreferences(Preferences.PREFS_NAME, Context.MODE_PRIVATE);
		activity_type = settings.getString(Preferences.CURRENT_TYPE, Preferences.SIT_TO_STAND);
		String activity_name = activity_type +"_" + date.getTime();
		db = new SampleDB(mContext);
		activity_id = (int) db.addActivityName(activity_name);

	}

	@Override
	public void onAccuracyChanged(Sensor arg0, int arg1) {
		// TODO Auto-generated method stub

	}

	@Override
	public void onSensorChanged(SensorEvent event) {
		Date date = new Date();
		db.addSample(new Sample(event.values[0],event.values[1],event.values[2],
				date.getTime(),activity_type,activity_id));
		//Log.i(TAG,event.values[0] + ":" + event.values[1]+ ":" + event.values[2] +activity_type + " " + activity_id);
	}

}
